openapi: 3.0.0
info:
  title: germanzero
  version: '1.0'
  license:
    name: MIT
  description: An API to access GermanZero
servers:
  - url: 'http://localhost:3000'
    description: 'Local development'
  - url: 'https://api.gz.dilab.co'
    description: 'Live server'
    
paths:
  /contacts:
    post:
      summary: 'Create a new contact in CRM'
      responses:
        '202':
          description: Created but must be confirmed
        '409':
          description: Conflict
      description: Create a new GermanZero contact
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/member'
            examples:
              example:
                value:
                  firstName: John
                  lastName: Doe
                  email: johndoe@example.com

  /contacts/:contactId/confirmations/:code:
    get:
      summary: 'Marks the email address of the contact as confirmed'
      description: Contacts are firstly created opted out from mailings to comply with GDPR. A first email is sent then, containin a confirmation link which is this route.
      responses:
        '200':
          description: Contact is confirmed
        '400':
          description: Invalid code

  /members:
    post:
      summary: ''
      responses:
        '201':
          description: Created
        '409':
          description: Conflict
      description: Create a new GermanZero member
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/member'
                - type: object
                  properties:
                    password:
                      type: string
                      description: Initial password
            examples:
              example:
                value:
                  firstName: John
                  lastName: Doe
                  email: johndoe@example.com
                  password: my-great-secret
components:
  schemas:
    member:
      title: member
      type: object
      description: Representation of a GermanZero member record
      properties:
        id:
          type: string
          description: Automatic generated identifier for member
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
      required:
        - firstName
        - lastName
        - email
      x-examples:
        example:
          value:
            firstName: John
            lastName: Doe
            email: johndoe@example.com
  securitySchemes:
    APIKey:
      name: API Key
      type: apiKey
      in: header
